version: '3.8'

services:
  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: account_service
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  neo4j:
    image: neo4j:5
    environment:
      NEO4J_AUTH: neo4j/12345678
    ports:
      - "7474:7474"  # HTTP UI
      - "7687:7687"  # Bolt protocol
    volumes:
      - neo4j_data:/data

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"     # AMQP protocol (ứng dụng dùng)
      - "15672:15672"   # UI Web quản lý
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

volumes:
  mysql_data:
  neo4j_data:
  rabbitmq_data:
